lecture-2 functions have been added
bOOmerSpb/lukogorskii-python pull request #2
Opened 2021-04-05 09:08 UTC by bOOmerSpb

All hw tasks for lecture 2 are included

2021-04-20 19:42 UTC, zhidelev requested changes
Поправить небольшие замечания и можно снова на проверку 👍

2021-04-20 19:42 UTC, zhidelev commented on Lecture_2_Collections_homework/hw1.py
> +    return len(line.split(" ")) == 5
Предварительно `strip()` делать не надо.  `split()` разделит по пробелам, табам и проч. , поэтому можно сделать просто `return len(line.split()) == 5`

2021-04-20 19:42 UTC, zhidelev commented on Lecture_2_Collections_homework/hw2.py
> +        return inp[-1], inp[0]
Это будет работать, если у тебя 2 уникальных элемента. 
Посмотри в сторону https://docs.python.org/3/library/collections.html#collections.Counter

2021-04-22 09:34 UTC, bOOmerSpb commented on Lecture_2_Collections_homework/hw1.py
> +    return len(line.split(" ")) == 5
сделал

2021-04-22 09:34 UTC, bOOmerSpb commented on Lecture_2_Collections_homework/hw2.py
> +        return inp[-1], inp[0]
поправил

2021-04-26 18:14 UTC, zhidelev approved these changes
👍

2021-04-26 18:17 UTC, merged