Lecture 4
bOOmerSpb/lukogorskii-python pull request #4
Opened 2021-04-22 13:16 UTC by bOOmerSpb

2021-04-22 20:21 UTC, zhidelev requested changes
Поправить комментарии и снова на ревью.

2021-04-22 20:21 UTC, zhidelev commented on Lecture_4_Testing_homework/cf_function.py
> +    denominator = int(fraction.split("/")[1])
Тут можно применить unpacking `numerator, denominator = map(int, fraction.split("/"))`

2021-04-22 20:21 UTC, zhidelev commented on Lecture_4_Testing_homework/cf_function.py
> +        first = math.floor(num / denom)
Можно использовать builtin, а не импортировать math
`num // denom`

2021-04-22 20:21 UTC, zhidelev commented on Lecture_4_Testing_homework/cf_test.py
> +
Добавь ещё тест с denominator = 0.

2021-04-23 07:17 UTC, bOOmerSpb commented on Lecture_4_Testing_homework/cf_function.py
> +    denominator = int(fraction.split("/")[1])
сделано

2021-04-23 07:18 UTC, bOOmerSpb commented on Lecture_4_Testing_homework/cf_function.py
> +        first = math.floor(num / denom)
поменял

2021-04-23 07:45 UTC, bOOmerSpb commented on Lecture_4_Testing_homework/cf_test.py
> +
добавил

2021-04-26 17:46 UTC, zhidelev approved these changes
👍

2021-04-26 18:00 UTC, merged