Lesson 6 OOP2
bOOmerSpb/lukogorskii-python pull request #6
Opened 2021-04-25 21:16 UTC by bOOmerSpb

2021-05-13 16:00 UTC, ZoiaOchikova requested changes

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, message='You are late'):
init писать не обязательно только чтоб вывести нужное сообщение. Достаточно будет написать вот так `DeadlineError('You are late')`, когда нужно будет его бросить.

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +        super().__init__(first_name, last_name)
Если нет никакой дополнительной логики в ините наследника, то его не обязательно писать, инит предка вызовется автоматически.

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +                Teacher.homework_done[key] = value
У тебя получается, что если два студента сделали хорошо задание, то запишется результат только последнего из них.
И еще записывать в `homework_done` надо объекты типа `HomeworkResult`

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
Здесь ожидается максимум один аргумент, поэтому мне кажется удобнее передавать сразу этот аргумент с дефолтным значением.

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, first_name: str, last_name: str):
Этот инит тоже можно убрать

2021-05-13 16:00 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +        self.created = homework.created
Мне кажется здесь нужно время создания объекта `HomeworkResult`

2021-05-13 19:20 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, message='You are late'):
Не совсем понял, по заданию нужно ведь поднять именно исключение с таким сообщением. Поэтому инит и дефолтное сообщение в нем

2021-05-13 19:23 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +        super().__init__(first_name, last_name)
поправил

2021-05-13 19:23 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, first_name: str, last_name: str):
поправил

2021-05-13 19:25 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +        self.created = homework.created
поменял

2021-05-13 19:26 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
Здесь непонятно же, сколько аргументов передается: ниодного или один - потому и так они передаются, в теле же функции как раз это проверяется

2021-05-13 19:51 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +                Teacher.homework_done[key] = value
поправил запись объектов HomeworkResults в homework_done
По поводу первого замечания не очень понял, что не так, для каждого студента свое домашнее задание и все провреренные дз хранятся в homework_done. Я пробовал вызывать принт для другого одновременно с первым в main - все ок

2021-05-13 20:51 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, message='You are late'):
Имеелось ввиду, что сам класс выглядит так?
class DeadlineError(Exception):
    pass

а в методе do_homework следующим образом?
        else:
            raise DeadlineError('You are late')

2021-05-18 11:28 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, message='You are late'):
одновил, как указал в комментарии выше

2021-05-18 11:29 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
не сразу понял замечание, теперь обновил

2021-05-18 14:58 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +                Teacher.homework_done[key] = value
<img width="723" alt="Screenshot 2021-05-18 at 17 50 18" src="https://user-images.githubusercontent.com/37502909/118674189-44e16680-b802-11eb-9619-0cb8c573f9ce.png">

Я сделала скриншот кода, где есть 2 студента, которые сделали одно и то же задание. В homework_done по итогу оказалось только последнее из них (выделено красным). Так получилось, тк был использован homework в качестве ключа, который одинаковый для обоих студентов (выделено синим).
Надеюсь скриншот загрузился :)

2021-05-18 15:31 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
В данном случае в качестве дефолтного значения лучше использовать None

2021-05-18 15:49 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def __init__(self, message='You are late'):
В целом по условию твой вариант тоже подходил, но второй, как мне кажется, лаконичнее

2021-05-18 19:23 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
Все же исправил)

2021-05-18 20:53 UTC, bOOmerSpb commented on Lecture_6_OOP2_homework/oop_2.py
> +                Teacher.homework_done[key] = value
вроде наконец дошло до меня - обновил на использование списков, как value для словаря

2021-05-20 13:10 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +        if len(value) > 5 and result not in Teacher.homework_done[key]:
Можно использовать set вместо list и тогда проверка не нужна была бы

2021-05-20 13:10 UTC, ZoiaOchikova approved these changes

2021-05-20 17:47 UTC, merged